# Generated by Django 2.0.3 on 2018-03-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180326_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_time',)},
        ),
    ]
